# Copyright Nathan L Smith <smith@nlsmith.com>
# SPDX-License-Identifier: Apache-2.0

# TODO: Otel export logs from docker compose?
# TODO: Issue with slave when running otel demo https://elastic.slack.com/archives/C031284ANNL/p1728500190563419

# [Compose file](https://docs.docker.com/reference/compose-file/) for Elastic stack
name: elastic-stack-docker-compose
include:
  - setup_compose.yaml
  - profiling_compose.yaml
  - apm_server_compose.yaml
  - otel_collector_compose.yaml
configs:
  elasticsearch.yml:
    file: config/elasticsearch.yml
  kibana.yml:
    file: config/kibana.yml
  node.options:
    file: config/node.options
services:
  elasticsearch:
    configs:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    container_name: elasticsearch
    depends_on:
      setup_certs:
        condition: service_completed_successfully
    develop:
      watch:
        - action: sync+restart
          path: config/elasticsearch.yml
          target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ELASTIC_PASSWORD
      - cluster.name="${ES_CLUSTER_NAME}"
      - xpack.license.self_generated.type="${ES_LICENSE}"
    healthcheck:
      interval: 2s
      retries: 120
      test:
        - CMD-SHELL
        - curl -s --cacert config/certs/ca/ca.crt https://localhost:${ES_PORT} | grep -q 'missing authentication credentials'
      timeout: 10s
    hostname: host.docker.internal
    image: ${ES_IMAGE}
    mem_limit: ${ES_MEM_LIMIT}
    ports:
      - ${ES_PORT}:${ES_PORT}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
      - eslogs:/usr/share/elasticsearch/logs
  kibana:
    # TODO: Turn on EEM
    # TODO: Error initializing AI assistant resources: Platinum, Enterprise or trial license needed
    # TODO generate encryption keys
    # TODO: Set up alerts for services/hosts on boot
    # TODO: inspect logs queries to the kibana console but it should do them at DEBUG level not WARN
    configs:
      - source: kibana.yml
        target: /usr/share/kibana/config/kibana.yml
      - source: node.options
        target: /usr/share/kibana/config/node.options
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
      setup_kibana_user:
        condition: service_completed_successfully
    develop:
      watch:
        - action: sync+restart
          path: config/kibana.yml
          target: /usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:${ES_PORT}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      interval: 10s
      retries: 120
      test:
        - CMD-SHELL
        - curl -s --cacert config/certs/ca/ca.crt https://localhost:5601/api/status
      timeout: 10s
    hostname: host.docker.internal
    image: ${KIBANA_IMAGE}
    mem_limit: ${ES_MEM_LIMIT}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    restart: unless-stopped
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibana_data:/usr/share/kibana/data
      - kibana_logs:/usr/share/kibana/logs
volumes:
  bin:
    driver: local
  certs:
    driver: local
  esdata:
    driver: local
  eslogs:
    driver: local
  etc:
    driver: local
  kibana_data:
    driver: local
  kibana_logs:
    driver: local
  # See https://github.com/elastic/elastic-agent/blob/main/internal/pkg/otel/README.md#persistence-in-standalone-docker-mode
  otel_registry:
    driver: local
