 # [Elasticsearch configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html)
bootstrap.memory_lock: true
discovery.type: single-node
ingest.geoip.downloader.enabled: false
logger.org.elasticsearch: WARN
node.name: elastic-stack-docker-compose-es-node-0
xpack.security:
  enabled: true
  http.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
  http.ssl.certificate: certs/elasticsearch/elasticsearch.crt
  http.ssl.enabled: true
  http.ssl.key: certs/elasticsearch/elasticsearch.key
  transport.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
  transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
  transport.ssl.enabled: true
  transport.ssl.key: certs/elasticsearch/elasticsearch.key
  transport.ssl.verification_mode: certificate
