# [Kibana configuration](https://github.com/elastic/kibana/blob/main/config/kibana.yml)
elasticsearch:
  username: kibana_system
  ssl:
    certificateAuthorities: [ "config/certs/ca/ca.crt" ]
    verificationMode: full
logging.root.level: warn

uiSettings.overrides.defaultRoute: /app/discover#/?_g=()&_a=(dataSource:(type:esql),filters:!(),query:(esql:'FROM%20logs-*%20%7C%20LIMIT%2010'))
uiSettings.overrides.observability:enableInspectEsQueries: true
uiSettings.overrides.observability:entityCentricExperience: true
# TODO: The ES|QL window is white when system darkmode is enabled.
uiSettings.overrides.theme:darkMode: system
uiSettings.overrides.observability:newLogsOverview: true
server:
  host: "0.0.0.0"
  shutdownTimeout: "5s"

xpack.encryptedSavedObjects.encryptionKey: 0c4fb61f013d771f43d321e5b2484f4d
xpack.reporting.encryptionKey: 369ecfa55ee4b9e8c3d5481c6589287a
xpack.reporting.roles.enabled: false
xpack.screenshotting.browser.chromium.disableSandbox: true
xpack.security.encryptionKey: 944c9b01e335cf7eebcda4413797f494
