# [Kibana configuration](https://github.com/elastic/kibana/blob/main/config/kibana.yml)
elastic.apm:
  #active: true
  transaction.sample.rate: 1
elasticsearch:
  username: kibana_system
  ssl:
    certificateAuthorities: [ "config/certs/ca/ca.crt" ]
    verificationMode: full
logging.root.level: warn
monitoring.ui.container.elasticsearch.enabled: true
server:
  host: "0.0.0.0"
  shutdownTimeout: "5s"
xpack.encryptedSavedObjects.encryptionKey: 0c4fb61f013d771f43d321e5b2484f4d
xpack.reporting.encryptionKey: 369ecfa55ee4b9e8c3d5481c6589287a
xpack.reporting.roles.enabled: false
xpack.screenshotting.browser.chromium.disableSandbox: true
xpack.security.encryptionKey: 944c9b01e335cf7eebcda4413797f494
